#!/usr/bin/env bash
#
# Populates app/assets/exiftool/ with the exiftool Perl distribution (the
# `exiftool` script + its `lib/Image/...` modules) so it gets bundled into the
# app at `flutter build` time. Kept out of git (~39MB) and regenerated here.
#
# Run before `flutter build` (CI does this). Strategy:
#   1. If a system exiftool is installed, vendor its real distribution.
#   2. Otherwise download the official tarball from exiftool.org.
#
# macOS/Linux invoke the vendored script via the system `perl`. Windows builds
# should instead drop the official self-contained exiftool.exe here (TODO).

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$REPO_ROOT/app/assets/exiftool"
PUBSPEC="$REPO_ROOT/app/pubspec.yaml"

# Rewrites the marked block in app/pubspec.yaml with one `- assets/exiftool/<d>/`
# entry per subdirectory that contains files. Flutter's `assets:` is
# non-recursive, so the whole vendored tree must be enumerated.
regenerate_pubspec_assets() {
  local begin="    # --- BEGIN exiftool assets (generated by tool/fetch-exiftool.sh) ---"
  local end="    # --- END exiftool assets ---"
  local entries_file
  entries_file="$(mktemp)"
  # Every subdir of assets/exiftool/ that holds at least one file, as paths
  # relative to app/, sorted and deduped, formatted as pubspec asset lines.
  (cd "$REPO_ROOT/app" && find assets/exiftool -type f -exec dirname {} \; \
    | sort -u | sed 's#^#    - #; s#$#/#') >"$entries_file"
  awk -v begin="$begin" -v end="$end" -v entries_file="$entries_file" '
    $0 == begin {
      print begin
      print "    # Flutter assets: is non-recursive; every subdir is listed."
      while ((getline line < entries_file) > 0) print line
      close(entries_file)
      skip = 1
      next
    }
    $0 == end { print end; skip = 0; next }
    skip != 1 { print }
  ' "$PUBSPEC" >"$PUBSPEC.tmp" && mv "$PUBSPEC.tmp" "$PUBSPEC"
  rm -f "$entries_file"
  echo "regenerated exiftool asset list in $PUBSPEC"
}

if [ -f "$DEST/lib/Image/ExifTool.pm" ]; then
  echo "exiftool already vendored at $DEST"
  regenerate_pubspec_assets
  exit 0
fi

mkdir -p "$DEST"

vendor_from_system() {
  command -v exiftool >/dev/null 2>&1 || return 1
  local real libroot
  real="$(command -v exiftool)"
  # Resolve the install's lib root that contains Image/ExifTool.pm.
  for cand in \
    "$(dirname "$real")/../libexec/lib/perl5" \
    "$(dirname "$real")/../lib/perl5" \
    "$(dirname "$real")/../libexec/lib"; do
    if [ -f "$cand/Image/ExifTool.pm" ]; then libroot="$cand"; break; fi
  done
  [ -n "${libroot:-}" ] || return 1
  cp "$real" "$DEST/exiftool"
  chmod +x "$DEST/exiftool"
  cp -R "$libroot/." "$DEST/lib/"
  return 0
}

vendor_from_download() {
  local ver tar
  ver="$(curl -fsSL https://exiftool.org/ver.txt 2>/dev/null || true)"
  [ -n "$ver" ] || return 1
  tar="$(mktemp -d)/et.tgz"
  curl -fsSL "https://exiftool.org/Image-ExifTool-${ver}.tar.gz" -o "$tar" || return 1
  tar xzf "$tar" -C "$(dirname "$tar")"
  local src="$(dirname "$tar")/Image-ExifTool-${ver}"
  cp "$src/exiftool" "$DEST/exiftool"; chmod +x "$DEST/exiftool"
  cp -R "$src/lib/." "$DEST/lib/"
  return 0
}

mkdir -p "$DEST/lib"
if vendor_from_system; then
  echo "vendored exiftool from the system install"
elif vendor_from_download; then
  echo "vendored exiftool from exiftool.org"
else
  echo "ERROR: could not vendor exiftool (no system install and download failed)" >&2
  exit 1
fi

if perl "$DEST/exiftool" -ver >/dev/null 2>&1; then
  echo "OK: $(perl "$DEST/exiftool" -ver) at $DEST"
else
  echo "ERROR: vendored exiftool does not run via 'perl'" >&2
  exit 1
fi

regenerate_pubspec_assets
